#CI de nivel 01 - Disparo manual apartir de 1 clique 
name: 'Execução Manual'

#regras de disparos (gatilhos/triggers)
#gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:
 
 #trabalhos/tarefas dentro da pipeline = jobs
jobs:
  e2e-tests:

  #maquina que o job vai executar
    runs-on: ubuntu-latest

  #passos do script de build
    steps:
    #clone do projeto
      - uses: actions/checkout@v3
        
    #instalaçãoes do node 
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
    
    #instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

    #instalação das dependencias
      - name: Instalando dependências
        run: yarn

    #instalando os testes e2e
      - name: Executando testes com Mocha
        run: npx mocha trabalho/trabalho-final.js

    #gerar relatorio sobre a execução manual
      - name: Upload do artefato gerado
        uses: actions/upload-artifact@v4
        with:
          name: resultado-dos-testes
          path: relatorios/teste-output.json